In [1]:
# 导入numpy库，并且重命名为np
import numpy as np

In [3]:
# 打印numpy的版本和配置说明
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    fou

In [4]:
# 创建一个长度为10的空向量
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 找到任何一个数组的内存大小
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [10]:
# 如何得到numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
# 创建一个长度为10并且除了第五个值为1的空向量
data = np.zeros(10)
data[4] = 1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
# 创建一个值域范围从10到49的向量
data = np.arange(10, 50)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
# 创建一个值域范围从10到49的向量，并将其反转
data = np.arange(50)
data = data[::-1]
data

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [16]:
# 创建一个 3x3 并且值从0到8的矩阵
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# 找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4], dtype=int64),)

In [18]:
# 创建一个 3x3 的单位矩阵
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 创建一个 3x3x3的随机数组
a = np.random.random((3, 3, 3))
a

array([[[0.43756933, 0.26727765, 0.11802796],
        [0.54122957, 0.13562765, 0.48612115],
        [0.23970144, 0.38740128, 0.30448283]],

       [[0.66553607, 0.21120594, 0.17885151],
        [0.49756044, 0.22554073, 0.81471714],
        [0.98710133, 0.91168815, 0.68062364]],

       [[0.62260737, 0.65053648, 0.08895737],
        [0.59180725, 0.80885572, 0.07586314],
        [0.40992349, 0.90373251, 0.67097377]]])

In [21]:
# 创建一个 10x10 的随机数组并找到它的最大值和最小值
a = np.random.random((10, 10))
a_min, a_max = a.min(), a.max()
print(a_min, a_max)

0.0017971399809187938 0.9749136057620207


In [22]:
# 创建一个长度为30的随机向量并找到它的平均值
a = np.random.random(30)
a_mean = a.mean()
print(a_mean)

0.5955858656526212


In [24]:
# 创建一个二维数组，其中边界值为1，其余值为0
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
# 对于一个存在数组，如何添加一个用0填充的边界?
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [4]:
# 以下表达式运行的结果分别是什么?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [29]:
# 创建一个 5x5 的矩阵，并设置值1,2,3,4落在其对角线下方位置
data = np.diag(1 + np.arange(4), k=-1)
data

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [7]:
# 创建一个 8x8 的矩阵，并且设置成棋盘样式
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [8]:
# 考虑一个（6，7，8）形状的数组，其第100个元素的索引（x，y，z）是什么?
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [3]:
# 用tile函数去创建一个 8x8 的棋盘样式矩阵
a = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [5]:
# 对一个5x5的随机矩阵做标准化
a = np.random.random((5, 5))
a = (a - np.mean(a)) / (np.std(a))
a

array([[ 0.82021601,  0.47170265,  0.82673246,  0.20648658,  1.32615204],
       [-1.36569272, -1.4857836 , -0.37193898, -0.22050461,  0.69606646],
       [-0.62470513, -1.58221919, -0.088527  ,  1.31917518,  1.26946399],
       [-1.62702963,  1.32785559,  0.68551059,  0.54156393, -1.55842263],
       [-0.56294303, -0.42303121,  1.32275875, -0.02304412, -0.87984239]])

In [10]:
# 创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype
color = np.dtype([  ("r", np.ubyte, 1),
                    ("g", np.ubyte, 1),
                    ("b", np.ubyte, 1),
                    ("a", np.ubyte, 1)  ])
color

C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_11316\373753137.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([  ("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [8]:
# 一个5x3的矩阵和一个3x2的矩阵相乘，实矩阵的积是什么?

# a = np.dot(np.ones((5, 3)), np.ones((3, 2)))
# a

a = np.ones((5, 3)) @ np.ones((3, 2))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [9]:
# 给定一个一维数组，对其在3到8之间的所有元素取反
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [3]:
# 下面脚本运行后的结果是什么?
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [8]:
# 考虑一个整数向量Z，下列表达合法的是哪个?
Z = np.arange(5, dtype=int)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)    
# Z<Z>Z

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


In [10]:
# 下列表达式的结果分别是什么?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_17432\3387418362.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_17432\3387418362.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [5]:
# 如何从零位对浮点数组做舍入 ?
a = np.random.uniform(-10,+10,10)
print(a)
print (np.copysign(np.ceil(np.abs(a)), a))

[ 7.49281917 -0.06405908 -4.06099375  2.28878669  3.06885067 -5.5183765
 -2.75808223  0.97686766 -1.01455021  0.93439706]
[ 8. -1. -5.  3.  4. -6. -3.  1. -2.  1.]


In [6]:
# 如何找到两个数组中的共同元素?
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[1 7 9]


In [2]:
# 如何忽略所有的 numpy 警告（尽管不建议这么做）?
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [4]:
np.seterr(**defaults)
Z = np.ones(1) / 0

C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_11704\3746067005.py:2: RuntimeWarning: divide by zero encountered in true_divide
  Z = np.ones(1) / 0


In [6]:
# 下面的表达式是正确的吗?
#   nan            1j
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\KOBAYASHI\AppData\Local\Temp\ipykernel_11704\3648233374.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [8]:
# 如何得到昨天，今天，明天的日期?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"yesterday: {yesterday} today: {today} tomorrow: {tomorrow}")

yesterday: 2022-12-20 today: 2022-12-21 tomorrow: 2022-12-22


In [9]:
# 如何得到所有与2016年7月对应的日期？
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [11]:
# 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [12]:
# 用五种不同的方法去提取一个随机数组的整数部分
a = np.random.uniform(0, 10, 10)
print(a - a%1)

[1. 3. 1. 5. 5. 2. 2. 2. 9. 6.]


In [13]:
# 创建一个5x5的矩阵，其中每行的数值范围从0到4
a = np.zeros((5, 5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [15]:
# 通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(), dtype=float, count=-1) # a = np.fromiter((x for x in range(10)), dtype=float, count=-1)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
# 创建一个长度为10的随机向量，其值域范围从0到1，但不包括0和1
a = np.linspace(0, 1, 11, endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [22]:
# 创建一个长度为10的随机向量，并将其排序
a = np.random.randint(0, 10, 10)
a.sort()
a

array([0, 1, 2, 2, 3, 5, 6, 7, 7, 9])

In [23]:
# 对于一个小数组，如何用比 np.sum更快的方式对其求和？
a = np.arange(10)
np.add.reduce(a)

45

In [27]:
# 对于两个随机数组A和B，检查它们是否相等
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)
np.allclose(a, b)


False

In [28]:
# 创建一个只读数组(read-only)
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [30]:
# 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
z = np.random.random((10,2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y, x)
print(r)
print(t)

[0.78991835 0.47107172 0.6532637  0.88302193 0.66694681 0.78696029
 1.17305675 0.2819286  0.56842421 0.76234967]
[0.70750139 0.67671178 0.8882485  1.46483816 1.39379161 1.46829534
 0.76148733 0.2450285  0.96245817 1.19602676]


In [ ]:
# 创建一个长度为10的向量，并将向量中的最大值替换为1