In [2]:
# 导入numpy库，并且重命名为np
import numpy as np

In [3]:
# 打印numpy的版本和配置说明
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Program/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Program/Anaconda\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    fou

In [4]:
# 创建一个长度为10的空向量
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 找到任何一个数组的内存大小
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [10]:
# 如何得到numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
# 创建一个长度为10并且除了第五个值为1的空向量
data = np.zeros(10)
data[4] = 1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
# 创建一个值域范围从10到49的向量
data = np.arange(10, 50)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
# 创建一个值域范围从10到49的向量，并将其反转
data = np.arange(50)
data = data[::-1]
data

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [16]:
# 创建一个 3x3 并且值从0到8的矩阵
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# 找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4], dtype=int64),)

In [18]:
# 创建一个 3x3 的单位矩阵
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 创建一个 3x3x3的随机数组
a = np.random.random((3, 3, 3))
a

array([[[0.43756933, 0.26727765, 0.11802796],
        [0.54122957, 0.13562765, 0.48612115],
        [0.23970144, 0.38740128, 0.30448283]],

       [[0.66553607, 0.21120594, 0.17885151],
        [0.49756044, 0.22554073, 0.81471714],
        [0.98710133, 0.91168815, 0.68062364]],

       [[0.62260737, 0.65053648, 0.08895737],
        [0.59180725, 0.80885572, 0.07586314],
        [0.40992349, 0.90373251, 0.67097377]]])

In [21]:
# 创建一个 10x10 的随机数组并找到它的最大值和最小值
a = np.random.random((10, 10))
a_min, a_max = a.min(), a.max()
print(a_min, a_max)

0.0017971399809187938 0.9749136057620207


In [22]:
# 创建一个长度为30的随机向量并找到它的平均值
a = np.random.random(30)
a_mean = a.mean()
print(a_mean)

0.5955858656526212


In [24]:
# 创建一个二维数组，其中边界值为1，其余值为0
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
# 对于一个存在数组，如何添加一个用0填充的边界?
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])